"""
summarizer.py — Turn triaged + enriched alerts into an analyst-ready
incident summary using the Claude API.

Requires ANTHROPIC_API_KEY in the environment. If it's missing, falls back
to a deterministic, template-based summary so the pipeline still runs
end-to-end offline (useful for tests / CI).
"""

from __future__ import annotations

import json
import os
from typing import Any

from . import config
from .logging_setup import get_logger

logger = get_logger(__name__)

try:
    import anthropic
except ImportError:  # pragma: no cover
    anthropic = None

SYSTEM_PROMPT = """You are a Tier-2 SOC analyst assistant. You are given a batch of \
already-deduplicated, scored, and IOC-enriched security alerts. Write a concise \
incident summary for a human analyst. Structure your response as:

1. Headline (one line, plain language, what's likely happening)
2. Top priority items (P1/P2 only, bullet points, include the IOC verdicts and \
   MITRE ATT&CK technique if present)
3. Recommended next actions (concrete, ordered by urgency — e.g. isolate host, \
   block IP at firewall, reset credentials, escalate to IR)
4. Notable false-positive risk (if any alert looks like benign/expected activity, say so)

Be concise and skip alerts that are clearly low-severity noise (P4) unless the \
volume itself is suspicious. Do not invent IOCs, timestamps, or scores that are \
not present in the input.
"""


def _fallback_summary(triaged_alerts: list[dict[str, Any]]) -> str:
    """Deterministic summary used when the Claude API isn't available."""
    p1 = [a for a in triaged_alerts if a.get("priority_tier") == "P1"]
    p2 = [a for a in triaged_alerts if a.get("priority_tier") == "P2"]
    lines = [f"Incident batch: {len(triaged_alerts)} alerts after dedup."]
    if p1:
        lines.append(f"\n{len(p1)} P1 (critical) alert(s):")
        for a in p1:
            lines.append(f"  - [{a['priority_score']}] {a.get('signature')} "
                          f"src={a.get('src_ip')} dest={a.get('dest_ip')} "
                          f"(x{a.get('occurrence_count', 1)})")
    if p2:
        lines.append(f"\n{len(p2)} P2 (high) alert(s):")
        for a in p2:
            lines.append(f"  - [{a['priority_score']}] {a.get('signature')} "
                          f"src={a.get('src_ip')} dest={a.get('dest_ip')}")
    if not p1 and not p2:
        lines.append("No P1/P2 alerts in this batch — likely routine noise, spot-check P3s.")
    lines.append("\n[Note: generated by offline fallback — set ANTHROPIC_API_KEY for a full AI summary.]")
    return "\n".join(lines)


def _compact_for_prompt(triaged_alerts: list[dict[str, Any]], max_alerts: int = 25) -> str:
    """Trim/shape alert dicts down to what the model needs, to save tokens."""
    compact = []
    for a in triaged_alerts[:max_alerts]:
        compact.append({
            "id": a.get("id"),
            "priority_tier": a.get("priority_tier"),
            "priority_score": a.get("priority_score"),
            "signature": a.get("signature"),
            "severity": a.get("severity"),
            "occurrence_count": a.get("occurrence_count", 1),
            "src_ip": a.get("src_ip"),
            "dest_ip": a.get("dest_ip"),
            "user": a.get("user"),
            "mitre": a.get("mitre", []),
            "enrichment_verdicts": {
                field: data.get("verdict")
                for field, data in a.get("enrichment", {}).items()
            },
            "message": (a.get("message") or "")[:200],
        })
    return json.dumps(compact, ensure_ascii=False, indent=2)


def summarize_incident(triaged_alerts: list[dict[str, Any]]) -> str:
    """Produce an analyst-ready incident summary from a triaged+enriched alert list."""
    if not triaged_alerts:
        return "No alerts to summarize."

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key or anthropic is None:
        logger.info("ANTHROPIC_API_KEY not set or `anthropic` package missing — using offline fallback summary")
        return _fallback_summary(triaged_alerts)

    client = anthropic.Anthropic(api_key=api_key)
    payload = _compact_for_prompt(triaged_alerts)

    try:
        response = client.messages.create(
            model=config.ANTHROPIC_MODEL,
            max_tokens=1000,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": f"Alerts (JSON):\n{payload}"}],
        )
    except Exception:
        logger.exception("Claude API call failed while summarizing incident — using offline fallback summary")
        return _fallback_summary(triaged_alerts)

    text_blocks = [b.text for b in response.content if getattr(b, "type", None) == "text"]
    return "\n".join(text_blocks) if text_blocks else _fallback_summary(triaged_alerts)
